language: node_js
node_js:
- '8'
before_install:
- stty cols 80
env:
  global:
  - secure: qLUbjtVLS67vTzrD7MZafbIeP/k6+G0VVRfdDGdtKppa9skD0nakOkp9L534YKthlSeWz04QlgsGtWkL3H6YvRdOZuum+88nqI0os2TdUAt5gkXQClfUVcAPK0tvfX7geJ7SxUZoZ36+Ys1W/1meRElq5J+60I2gsg9Mais6kaIknRXvmCmSzF+/DcomnYeYy6nflCrr5fiMj6Ce44gAqNd8+hN5Ytb8Dhzq/p7tDpikwVXJIv+l034p/4rMVLFdcLNSIsIeSW2mV+eN4zzZNTrX5sFOWb34ytdCze53v7r43tusopE83KtyR+2xkrBp4oEtTSuFNXJnM/3NVhBdWENlCrCYtqx4Xr/ODlfzuZKvg19qHwJffBAjZHgkPuFN7L63XB2zUnVdoI648Zl1l5WkVvvmKE4oHa3VsLccLXetivowWVqYeZdSDUkO3bn+oBWWI4MNEVBynkxZlcdELUgJso0/voEpOUudhPHUqaWzetm4Fg7C1iN3Y8rIBhl6yoDRo4Xo+LuvKd7vuOQV2KkaXyg7nLomeFKKiwK8yyzA4msABgt+KiARV2b9Va/RNUSHcihGqbDZTkkhU9d1QI2F/buE1T3HFCfgaliMQhfZo8I2r5/kA3A0KbhhYCQD1tTLInZt+cEqkXrlisGteQCs14NYPrXbQRX7JhFaAj8=
  - secure: DrFR0qRjnVpexU1b5z9KNolqKAe0nZn8+T9+WGl6mHXtDmG0Nzx12oUZ8P0qZ1eWgFQ5dyWBC4w9tVEWS5I02Pxd5NuxxTyV+Fn/wi6n5CmO0tUKVt7K4eLNMVnEjFOn+ccSOhaoYejvJIvZVzGK8eFSnVtuNRDMz9uNC5aO+LNmHu0WwyUq+vKBEZd0QmaFxvGF0gafUnZV6xWFH5yNGA4L8gr1iGGxxgrsBKgcnbuW5/PXdKB/pc5S8fYebwioFMNK5+81vjLpjBhragAYou3k3FMRn0rNdj8xLQwoqAkeTU23Ljtk3mRoepbiVIVwTyAUHBvckrQGLNh7XLGVS7HTy1F/4ppbta3/bsDmfsZkAZ++5uivqdXVezjF1gRB6S8PpzrLhNL9/P0mJoOD6WvazJZIahzWhtuX7LODlygIH8rwOoxdAaCi4wohZwwB5ncV1JvTywLkTIB/WfqxXeXMBgv+VIu1WSY8vUZA6HRmkTG0/ywFHSlM8HGStPKr0ClVB1VNtyXmUFvSPhDaM0aT1IBZd5VaoXiQiNknEMzxhnL7q/y/7aXqiykrHSZhRMILeaUyiRkcjKOEwYGVjLMve+cEquihB/66tUeLb4QxmOE1ZtYqZTQ/9kQ629SwPZXGGeX8oLlrUzFemiD+Uug/BsAMioTLMQzAYl3X8ew=
sudo: required
addons:
  firefox: latest
  chrome: stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm install -g concurrently
script:
- npm run build_prod
- karma start --single-run
- http-server -p 7777 --silent &
- testcafe chrome testCafe/ --reporter minimal
before_deploy:
- tar -zcvf survey-creator.tar.gz build
- npm run doc_gen
deploy:
- provider: releases
  api_key:
    secure: Fe+bRA8WO1T345iLvXkrOusCkr9RTblojIGfTNV80sY9+Q5Zt7gPeDa2snvlvTWmdkN+y2vZzP73JN7HZv1kxg1egt9lFHvllGw6YTeka+CE74sPnHGMFx4OqJHtd4D0hLVXg5wM8BbgFJ4R+jqbLwWY2+brDY1hsM7bXSf17kjcUFhKCoyYMvHCr5cngf99igTaFDYFc3IcNMyfXgqsMiFR415v0CklfZiEQU4Tt2Eu8foC27hApzpSQVgLtIAsYPVVTFYD9yghRcpth5ouL5KTq83Qa/E7senwTJKHU1wBeOT/6BNwKxlXQrBzjAKTmNrB1KG0ES3UR5TuXocIid1+cEK1jUpwl7gldKYSdckTMTM1FDTZ7Wj2hrIof2NyPKIaiCk7c4Qlc61XR5zQCZF4n3Yyxtj9FLRkv+9DQpfKOS5yEqlAXqdU4s5kv3SN3FXMMDBNGv4szI1xMGKT+ld8rT2FnHJcrhn9QYlyCv/gahb3igOOC+1LRmo6oGHg3/ks8EeTOwMR/pOY0BuK6RxVoD2Da4ZD7pY9+/CthF9+1bcHaHeeQYWTs47NZijX/zawl/Xc65ktGCzav2hX9M0jWBckDiGRsB/34MuFvPGtuIFhJAxsb0PGO3bEEcMzMpdte9TxO0zlufoHRHpfifehbNKkmL2582fUiYS1ouI=
  file: survey-creator.tar.gz
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: chmod +x ./deploy_npm.sh && ./deploy_npm.sh
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: npm run doc_update
  skip_cleanup: true
notifications:
  email:
    recipients:
    - andrew.telnov@gmail.com
